// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZHw72q3lKCqFhdtNtYLTuVA94Wzqod7E',
    appId: '1:976828644099:web:6968ad1553113d0ede8736',
    messagingSenderId: '976828644099',
    projectId: 'luckystar-flutter-12d06',
    authDomain: 'luckystar-flutter-12d06.firebaseapp.com',
    storageBucket: 'luckystar-flutter-12d06.firebasestorage.app',
    measurementId: 'G-CNR1YFP1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTJdoRMMQn7RtX4ML5UBBvLgyQN9ctG0',
    appId: '1:976828644099:android:6ad39ee936b0837ade8736',
    messagingSenderId: '976828644099',
    projectId: 'luckystar-flutter-12d06',
    storageBucket: 'luckystar-flutter-12d06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLbYwteJqvPJt6OiydLwPsEp6-1b7K2pw',
    appId: '1:976828644099:ios:75cb2660deb1eca4de8736',
    messagingSenderId: '976828644099',
    projectId: 'luckystar-flutter-12d06',
    storageBucket: 'luckystar-flutter-12d06.firebasestorage.app',
    iosBundleId: 'app.cosmosoul.prod',
  );

}